name: Python application (Conda)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: '3.10'
    - name: Create and activate environment
      run: |
        conda env create -f Face Data/environment.yml || conda env update -f Face Data/environment.yml
        conda activate myenv
      shell: bash -l {0}
    - name: Run tests
      run: |
        # Add your test command here, e.g. pytest or unittest
        echo "No tests specified"
      shell: bash -l {0}
    - name: Build
      run: |
        echo "Build step (customize as needed)"
      shell: bash -l {0} 
