name: Setup Conda Environment

on: [push]

jobs:
  setup-conda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false
          python-version: 3.9

      - name: Create or Update Conda Environment
        run: |
          conda env create -f "Face Data/environment.yml" || conda env update -f "Face Data/environment.yml"
