name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Face Data/requirements.txt
    - name: Run tests
      run: |
        # Add your test command here, e.g. pytest or unittest
        echo "No tests specified"
    - name: Build
      run: |
        echo "Build step (customize as needed)" 
